### ISSUE TITLE
Develop a model where merged-blocks contain ONLY irreversible(final) blocks

### ISSUE THREAD

**Issue by sduchesneau** [dfuse-io/bstream#22]
Why ?
* To remove complexity when handling block-indexes, which currently depend on separate "irreversible-indexes"
* To remove delays when the filesource needs to read "previous files"  and wants to pre-load forkDB
* To fix current performance issues seen when irreversible-indexes are bigger than block indexes
* to remove lots of complex code (like the LIBGetter)

Proposed model:
* The merger will only create merged-block-files passed the LIB (when finality is reached)
* The merger will not delete the one-block-files when it merges them. It will only delete them once a configurable period of time is passed (ex: 48h)
* A new service, called the fork-resolver, will be able to read one-block-files for the configured period of time and provide the blocks that are needed to get back to the canonical chain.
* When a request is made to the firehose, 
  1. it checks in its HUB to see if it contains the startblock (or the cursor block).
  2. if it has it, it starts from live with the forkdb, etc.
  3. if the block is older than what's in the firehose hub, it starts from the filesource, WITHOUT a forkDB. When the filesource is closer to the HEAD, the JoiningSource starts the LiveSource, attached to a forkDB, and joins it with the filesource.
* The relayer needs a similar logic ^

TODO

- [ ] Modify the merger to keep old files based on parameter and to only merge final blocks
- [ ] Write and test the ForkResolver-from-oneblock-files (allowing multiple source file stores)
- [ ] Write and test the new JoiningSource logic
- [ ] Write and test the new BlockIndexProvider logic
- [ ] Determine how we validate that merged-block-files are adapted to this new paradigm (probably a failsafe in filesource to panic when something happens)
- [ ] Document the steps and commands needed for a firehose provider to migrate

**Comment by matthewdarwin** [comment]
When I read this proposal, it looks like now merged blocks will be identical between firehose providers.  This is great!  Thank you!

However since we are planning to have multiple firehose providers within The Graph ecosystem, it still doesn't handle the case of one provider (A) seeing a fork which is written to a one-block file and another provider (B) not having it.  Then a cursor on this fork from (A) is not resumable in the other provider (B).

In our own provider infrastructure, we would actually like to run multiple independent datacenters with each having their own firehose stack. Is there a way this proposal can be extended to allow the forkresolver reading from multiple one-block sources? Or we can build our own component that constantly watches the one block files and if they don't appear locally but we can see them on another remote s3, then copy them over.  [different S3 servers would have different AWS API KEYS, which means current environment variable configuration would need changes]

But that just helps failover between datacenters that we run.  Doesn't help in the case of a graph-node user failing over to a different (not us) firehose provider.

**Comment by matthewdarwin** [comment]
Can I also add to your todo list to re-process all the old merged blocks to remove all the forks out of them (as a 1 time migration thing)?   Or if this feature will be ready before we build our eth-firehose2 blocks, then not a problem.

**Comment by matthewdarwin** [comment]
Just wondering: could the one-block files that make it into a merged-block be removed?  Just keep the one-block files that are on a fork?

**Comment by sduchesneau** [comment]
* The merged blocks will indeed be identical between firehose providers.

> Then a cursor on this fork from (A) is not resumable in the other provider (B).

The case that you are describing, where a cursor points to a forked out block, is something that we are very aware of. There is no simple solution that addresses *all* the cases (there will always be the case where a firehose consumer got a cursor from a provider who is the only one to ever see that specific forked block...)
BUT, sharing one-block-files (through shared access to a distributed filesystem or some kind of "rsync-style" scheduled task between remote locations) will significantly increase the chance for a consumer to hit a producer that has seen his forked block. We are not planning of providing something built-in for that file syncing operation.

> Is there a way this proposal can be extended to allow the forkresolver reading from multiple one-block sources?

Yes! Just added this to the description. It does not add much complexity and I agree that it would help firehose operators in some cases.

> [...] re-process all the old merged blocks [...]

The firehose can be used with 'sfeth tools download-from-firehose' command to remove forked blocks from merged block files. This means that you won't have to re-process from *geth* nodes in any case. Most historically-reprocessed blocks will already contain only final blocks, but we can provide a validation tool.

> could the one-block files that make it into a merged-block be removed? Just keep the one-block files that are on a fork?

Mayyyybe..... we haven't all agreed on this detail yet. Some of us are worried about race conditions and keeping all the one-block-files for a reasonable period of time (24h, 48h or even 1 week) does seem like the simplest solution. 
(1 week on of blocks eth-mainnet is ~8GiB  and about 50k one-block-files)
I will experiment a little bit on this model in the next week.

**Comment by matthewdarwin** [comment]
This is done now?

**Comment by sduchesneau** [comment]
done since a long time
